flask_app/controllers/BlogsController.py
# import hashlib
# For Hashing Password

from flask_app import db
import json
# from ..models.pypies import Pypies 
from ..models.blogs import Blogs
from ..models.posts import Posts
# from ..models.votes import Votes

from flask import redirect,session,request,url_for,render_template,flash,jsonify

def index():
        blogs =[]
        results = db.session.query(Blogs).filter_by().all()
        db.session.close()
        for res in results:
                resPosts = db.session.query(Posts).filter_by(blog_id = res.id).all()
                db.session.commit()
                db.session.close()
                total_posts = 0

                for respost in resPosts:
                        total_posts +=1

                res.total_posts = total_posts
                blogs.append(res)

        return render_template('blogs.html',blogs=blogs)


def add():
        if 'Email' in session:
                return render_template('add_blog.html')
        else:
                return redirect(url_for("blogs.index"))

def edit():
        if 'Email' in session:
                return render_template('edit.html')
        else:
                return redirect(url_for("blogs.index"))

def blog():

        if 'Email' in session:
                if request.method == 'POST':
                        if request.form['action'] == 'update_blog':
                                blog_id = request.form['blog_id']
                                blog_name = request.form['blog_name']
                                blog_path = blog_name.replace(" ","_")
                                blog_check = db.session.query(Blogs).filter_by(blog_path = blog_path).first()
                                if  blog_check is None:
                                        blogData = db.session.query(Blogs).filter_by(id = blog_id).first()
                                        blogData.blog_name = blog_name
                                        blogData.blog_path = blog_path
                                        db.session.commit()
                                
                                        db.session.close()
                                        flash("Blog Updated Successfully","success")
                                        return redirect(url_for('blogs.blog'))
                                else:
                                        flash("Blog with that title already exists","danger")
                                        return redirect(url_for('blogs.blog'))
                else:

                        blogs =[]
                        results = db.session.query(Blogs).filter_by().all()
                        db.session.close()
                        for res in results:
                                resPosts = db.session.query(Posts).filter_by(blog_id = res.id).all()
                                db.session.commit()
                                db.session.close()
                                total_posts = 0

                                for respost in resPosts:
                                        total_posts +=1

                                res.total_posts = total_posts
                                blogs.append(res)

                        return render_template('blog.html',blogs=blogs)
        else:
                return redirect(url_for("blogs.index"))

def create():
        if 'Email' in session:
                if request.method=='POST':
                        if request.form['action'] == 'create_blog':
                                blog_name = request.form['blog_name']
                                blog_path = blog_name.replace(" ","_")
                                blog_path = blog_path.replace("?","_")
                                blog_path = blog_path.replace("@","_")
                                blog_check = db.session.query(Blogs).filter_by(blog_path = blog_path).first()
                                if blog_check is None:
                                        Info = {
                                                "blog_name": blog_name,
                                                "blog_path": blog_path
                                        }
                                        blog_add = Blogs(Info)
                                        db.session.add(blog_add)
                                        db.session.commit()
                                        db.session.close()
                                        flash("Blog Created Successfully","success")
                                        return redirect(url_for('blogs.existing'))
                                else:
                                        flash("Blog with that title already exists","danger")
                                        return redirect(url_for('blogs.create'))
                        
                        else:
                                flash("Blog with that title already exists","danger")
                                return redirect(url_for('dashboard.index'))
                else:
                        return render_template('create.html')

        else:
                return redirect(url_for("blogs.index"))

def existing():
        if 'Email' in session:
                if request.method == 'POST':
                        if request.form['action'] == 'create_post':
                                post_title = request.form['post_title']
                                post_description = request.form['post_description']
                                post_link = post_title.replace(" ","_")
                                post_link = post_link.replace("@","_")
                                post_link = post_link.replace("#","_")
                                post_link = post_link.replace("?","_")
                                blog_id = request.form['blog_id']
                                post_check = db.session.query(Posts).filter_by(post_link = post_link).first()
                                if post_check is None:
                                        Info = {
                                                "post_title": post_title,
                                                "post_description": post_description,
                                                "post_link": post_link,
                                                "blog_id": blog_id
                                        }
                                        post_add = Posts(Info)
                                        db.session.add(post_add)
                                        db.session.commit()
                                        db.session.close()
                                        flash("Post Created Successfully","success")
                                        return redirect(url_for('blogs.index'))
                                else:
                                        flash("Blog with that title already exists","danger")
                                        return redirect(url_for('blogs.create'))
                        elif request.form['action'] == 'update_post':
                                post_title = request.form['post_title']
                                post_description = request.form['post_description']
                                post_link = post_title.replace(" ","_")
                                post_link = post_link.replace("@","_")
                                post_link = post_link.replace("#","_")
                                post_link = post_link.replace("?","_")
                                post_id = int(request.form['post_id'])
                                post_check = db.session.query(Posts).filter(Posts.post_link == post_link, Posts.id != post_id).first()
                                db.session.close()
                                if post_check is None:
                                        postUpdate = db.session.query(Posts).filter_by(id = post_id).first()
                                        postUpdate.post_title = post_title
                                        postUpdate.post_description = post_description
                                        postUpdate.post_link = post_link
                                        db.session.commit()
                                        db.session.close()
                                        flash("Post Updated Successfully","success")
                                        return redirect(url_for('blogs.index'))
                                else:
                                        flash("Post with that title already exists","danger")
                                        return redirect(url_for('blogs.create'))
                        else:
                                flash("Post with that title already exists","danger")
                                return redirect(url_for('dashboard.index'))
                        
                else:
                        blogs = []
                        results  = db.session.query(Blogs).filter_by().all()
                        for res in results:
                                blogs.append(res)
                        return render_template('existing.html',blogs=blogs)

        else:
                return redirect(url_for("blogs.index"))

def edit_blog(blog_id):
        if 'Email' in session:
                blog = db.session.query(Blogs).filter_by(id=int(blog_id)).first()
                db.session.close()
                return render_template("update_blog.html",blog = blog )

        else:
                return redirect(url_for("blogs.index"))
def view_posts_to_edit(blog_id):
        if 'Email' in session:
                posts = []
                result_data = db.session.query(Posts).filter_by(blog_id=int(blog_id)).all()
                db.session.close()
                for res in result_data:
                        posts.append(res)


                print(posts)

flask_app/controllers/LoginController.py
from flask_app import db

from flask import redirect,session,request,url_for,render_template,flash,jsonify


def index():
        if 'Email' in session:
                return redirect(url_for("predictions.index"))
        else:
                if request.method=='POST':
                        email = request.form['email_address']
                        password = request.form['password']

                        if email == "admin@gmail.com" and password == "admin123":
                                session['Email'] = email
                                session['Name'] = "admin"
                                return redirect(url_for("dashboard.index"))

                        else:
                                flash("Invalid Credentials",'Danger')
                                return redirect(url_for("login.index"))
                else:
                        return render_template('login.html')

def logout_account():
        if 'Email' in session:
                session.clear()
                return redirect(url_for("login.index"))

        else:
                return redirect(url_for("login.index"))

flask_app/controllers/PredictionController.py
from flask import redirect,session,request,url_for,render_template,flash,jsonify
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.image import imread
import cv2
import random
import tensorflow as tf
from os import listdir
from sklearn.preprocessing import  LabelBinarizer
from keras.preprocessing.image import img_to_array
from sklearn.model_selection import train_test_split
from werkzeug.utils import secure_filename
from os.path import join, dirname, realpath

UPLOAD_FOLDER = 'static/uploads'
absPath = dirname(realpath(__file__)) + '/../'
UPLOADS_PATH = join(absPath, 'static/uploads')
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])

def index():
       return render_template('predictions.html')


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS



def upload():
    if 'files[]' not in request.files:
        resp = jsonify({'message' : 'No file part in the request'})
        resp.status_code = 400
        return resp
    files = request.files.getlist('files[]')


    
    for file in files:
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(UPLOADS_PATH, filename))

    #     
            dir = join(absPath, 'Dogs')
            root_dir = listdir(dir)
            image_list, label_list = [], []

            # Reading and converting image to numpy array
            for directory in root_dir:
                for files in listdir(f"{dir}/{directory}"):
                    image_path = f"{dir}/{directory}/{files}"
                    print(image_path)
                    image = cv2.imread(image_path)
                    image = img_to_array(image)
                    image_list.append(image)
                    label_list.append(directory)
            # print("FETCH COMPLETE TILL HERE")

    
            label_counts = pd.DataFrame(label_list).value_counts()
            label_counts

            num_classes = len(label_counts)
            num_classes

            image_list[0].shape

            label_list = np.array(label_list)

            x_train, x_test, y_train, y_test = train_test_split(image_list, label_list, test_size=0.2, random_state = 10)


            x_test = np.array(x_test, dtype=np.float16)/255.0

            x_test = x_test.reshape(-1,224, 224, 3)

    #         # Label binarizing
            lb = LabelBinarizer()
            y_train = lb.fit_transform(y_train)
            y_test = lb.fit_transform(y_test)

            model = tf.keras.models.load_model(join(absPath,"dog_species.h5"))
            print(model.summary())
    #         # Calculating test accuracy
            scores = model.evaluate(x_test, y_test)
            print(f"Test Accuracy: {scores[1]*100}")

    #         # Storing predictions
            y_pred = model.predict(x_test)



    #         # Finding max value from predition list and comaparing original value vs predicted
            labels = lb.classes_

            Result = labels[np.argmax(y_pred[4])]
            success = True
            print("Completed")

    resp = jsonify({
        'message' : 'Files successfully uploaded',
        'accuracy': str({scores[1]*100}),
        "Originally":str(labels[np.argmax(y_test[7])]),
        "Predicted":str(labels[np.argmax(y_pred[56])]),
        "Result": Result,
        "imageName": filename
        })
    resp.status_code = 200
    return resp
    # test_dir = "datasets/Test images/IDC/8863_idx5_x151_y1251_class0.png"

flask_app/controllers/ShowController.py
import imp
from flask_app import db
from ..models.blogs import Blogs
from ..models.posts import Posts
from flask import redirect,session,request,url_for,render_template,flash


def index(blog_path):
    print(blog_path)
    result = db.session.query(Blogs).filter_by(blog_path = blog_path).first()
    print(result)
    print(result.id)
    blog = result
    db.session.close()
    posts = []
    if not(result is None):
        resPosts = db.session.query(Posts).filter_by(blog_id = result.id).all()
        for res in resPosts:
            posts.append(res)
        return render_template("show.html",blog= blog,posts=posts)

    else:
        flash("That blog doesn't exist",'danger')
        return redirect(url_for('blogs.index'))

            
def post(blog_path,post_link):
    result = db.session.query(Blogs).filter_by(blog_path = blog_path).first()
    print(result)
    db.session.close()
    blog = result
    posts = []
    if not (result is None):
        resPosts = db.session.query(Posts).filter_by(post_link = post_link).first()
        posts = resPosts
        return render_template("show_post.html",blog= blog,posts=posts)

    else:
        flash("That post doesn't exist",'danger')
        return redirect(url_for('blogs.index'))

flask_app/views/blogs.py
from flask import Blueprint

from ..controllers.BlogsController import index,add,create,existing,edit,blog,post,edit_blog,view_posts_to_edit,edit_post
blogs  = Blueprint(
    'blogs',
    __name__,
    template_folder = 'templates'
)

blogs.route('/', methods=['GET'])(index)
blogs.route('/add', methods=['GET'])(add)
blogs.route('/add/create', methods=['GET','POST'])(create)
blogs.route('/add/existing', methods=['GET','POST'])(existing)
blogs.route('/edit', methods=['GET'])(edit)
blogs.route('/edit/blog', methods=['GET','POST'])(blog)

blogs.route('/edit/post', methods=['GET','POST'])(post)

blogs.route('/edit/blog/<blog_id>', methods=['GET'])(edit_blog)
blogs.route('/edit/blog/<blog_id>/posts', methods=['GET'])(view_posts_to_edit)
blogs.route('/edit/blog/<blog_id>/posts/<post_id>', methods=['GET'])(edit_post)

flask_app/views/login.py
from flask import Blueprint

from ..controllers.LoginController import index
login  = Blueprint(
    'login',
    __name__,
    template_folder = 'templates'
)

login.route('/', methods=['GET','POST'])(index)

flask_app/views/predictions.py
from flask import Blueprint

from ..controllers.PredictionController import index,upload
predictions  = Blueprint(
    'predictions',
    __name__,
    template_folder = 'templates'
)

predictions.route('/', methods=['GET'])(index)
predictions.route('/upload', methods=['POST'])(upload)

flask_app/views/show.py
from flask import Blueprint

from ..controllers.ShowController import index,post
show  = Blueprint(
    'show',
    __name__,
    template_folder = 'templates'
)

show.route('/<blog_path>', methods=['GET'])(index)
show.route('/<blog_path>/<post_link>', methods=['GET'])(post)

flask_app/templates/add_blog.html
{% extends "user_default.html" %} {% block title %}Add Blog{%endblock%} {%block
header%}
<style>
  .card:hover {
    opacity: 0.5;
  }
  a {
    text-decoration: none;
  }
</style>

{%endblock%} {%block content%}

<div class="container">
  <div class="row">
    <div class="col-6">
      <a href="/blogs/add/create">
        <div class="card m-5" style="width: 550px">
          <img
            class="card-img-top"
            src="../static/create_blog.jpg"
            alt="Card image"
          />
          <div class="card-body bg-warning">
            <h4 class="card-title text-light text-center">ADD CATEGORY</h4>
          </div>
        </div>
      </a>
    </div>
    <div class="col-6">
      <a href="/blogs/add/existing">
        <div class="card m-5" style="width: 430px">
          <img
            class="card-img-top"
            src="../static/existing_blog.jpg"
            alt="Card image"
          />
          <div class="card-body border">
            <h4 class="card-title text-center text-dark">ADD CONTENT</h4>
          </div>
        </div>
      </a>
    </div>
  </div>
</div>
{% endblock %}

flask_app/templates/blog_for_post.html
{% extends "user_default.html" %} {% block title %}Edit Blogs{%endblock%}
{%block header%}
<style>
  .box_background {
    text-decoration: none;
    background-color: black !important;
  }
  .box:hover {
    opacity: 0.7;
  }
</style>
{%endblock%} {%block content%}

<div class="container">
  <h3 class="mt-5 bg-warning text-center text-light py-3">Select A Blog</h3>

  {%for blog in blogs%}
  <a class="box_background" href="/blogs/edit/blog/{{blog.id}}/posts">
    <div class="box row my-2">
      <div class="col-12">
        <div class="card text-center">
          <div class="card-body p-0">
            <div class="row p-0 m-0">
              <div class="col-8 mx-auto mt-5 mb-4">
                <h5 class="card-title text-dark bg-transparent">
                  {{blog.blog_name}}
                </h5>
              </div>
              <div class="col bg-dark p-2 px-5">
                <h4 class="mx-auto mt-3 bg-dark text-light">
                  {{blog.total_posts}}
                </h4>
                <h6 class="p-0 m-0 text-warning">POSTS</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </a>
  {%endfor%}
</div>

{% endblock %}

flask_app/templates/blogs.html
{% extends "user_default.html" %} {% block title %}Blogs{%endblock%} {%block
header%}
<style>
  .box_background {
    text-decoration: none;
    background-color: black !important;
  }
  .box:hover {
    opacity: 0.7;
  }
</style>
{%endblock%} {%block content%}

<div class="container">
  <h3 class="mt-5 bg-warning text-center text-light py-3">
    Welcome
  </h3>
  {%for blog in blogs%}
  <a class="box_background" href="/show/{{blog.blog_path}}">
    <div class="box row my-2">
      <div class="col-12">
        <div class="card text-center">
          <div class="card-body p-0">
            <div class="row p-0 m-0">
              <div class="col-8 mx-auto mt-5 mb-4">
                <h5 class="card-title text-dark bg-transparent">
                  {{blog.blog_name}}
                </h5>
              </div>
              <div class="col bg-dark p-2 px-5">
                <h4 class="mx-auto mt-3 bg-dark text-light">
                  {{blog.total_posts}}
                </h4>
                <h6 class="p-0 m-0 text-warning">POSTS</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </a>
  {%endfor%}
</div>

{% endblock %}

flask_app/templates/create.html
{% extends "user_default.html" %} {% block title %}Create Blog{%endblock%}
{%block header%}
<style></style>

{%endblock%} {%block content%}

<div class="container">
  <form class="row g-3 m-5" action="{{url_for('blogs.create')}}" method="POST">
    <div class="col-12 d-flex justify-content-center">
      <input
        type="text"
        class="form-control fs-3 text-center border-warning"
        style="width: 350px; border-radius: 25px"
        id="Blog Name"
        name="blog_name"
        placeholder="Enter your blog name"
        required
        maxlength = "25"
      />
      <button
        type="submit"
        class="btn btn-success fs-3 ms-3"
        style="width: 55px; border-radius: 50px"
        name="action"
        value="create_blog"
      >
        <i class="fa fa-check" aria-hidden="true"></i>
      </button>
    </div>
  </form>
</div>
{% endblock %}

flask_app/templates/edit.html
{% extends "user_default.html" %} {% block title %}Edit {%endblock%} {%block
header%}
<style>
  .card:hover {
    opacity: 0.5;
  }
  a {
    text-decoration: none;
  }
</style>

{%endblock%} {%block content%}

<div class="container">
  <div class="row">
    <div class="col-6">
      <a href="/blogs/edit/blog">
        <div class="card m-5" style="width: 550px">
          <img
            class="card-img-top"
            src="../static/create_blog.jpg"
            alt="Card image"
          />
          <div class="card-body bg-warning">
             <h4 class="card-title text-light text-center">DELETE CATEGORY</h4>
          </div>
        </div>
      </a>
    </div>
    <div class="col-6">
      <a href="/blogs/edit/post">
        <div class="card m-5" style="width: 430px">
          <img
            class="card-img-top"
            src="../static/existing_blog.jpg"
            alt="Card image"
          />
          <div class="card-body border">
            <h4 class="card-title text-center text-dark">EDIT POST</h4>
          </div>
        </div>
      </a>
    </div>
  </div>
</div>
{% endblock %}

flask_app/templates/edit_post.html
{% extends "user_default.html" %} {% block title %}Edit Post{%endblock%} {%block
header%}
<style></style>

{%endblock%} {%block content%}

<div class="container my-5">
  <div class="container" style="width: 70%">
    <form
      class="row g-3 border border-warning py-2"
      action="{{url_for('blogs.post')}}"
      method="POST"
    >
      <div class="col-12">
        <h3 class="text-light bg-warning text-center p-2">Update a Post</h3>
      </div>
      <div class="col-12">
        <label for="Blog Name" class="form-label">Blog Name</label>

        <select
          class="form-select border border-warning"
          onchange="FetchPost()"
          name="blog_id"
          id="blog_id"
          required
        >
          <option value="" hidden selected>Select a blog category</option>
          {%for blog in blogs %}
          <option value="{{blog.id}}">{{blog.blog_name}}</option>
          {%endfor%}
        </select>
      </div>

      <div class="col-12">
        <label for="post_title" class="form-label">Post Title</label>
        <input
          type="text"
          class="form-control border border-warning"
          id="post_title"
          name="post_title"
          required
        />
      </div>

      <div class="col-12">
        <label for="post_description" class="form-label"
          >Post Description</label
        >
        <textarea
          class="form-control border border-warning"
          style="height: 250px !important"
          id="post_description"
          name="post_description"
          width="100%"
          required
        ></textarea>
      </div>

      <div class="col-12 d-flex justify-content-center">
        <button
          type="submit"
          class="btn btn-success"
          name="action"
          value="create_post"
        >
          Update Post
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %} {%block Scripts%}
<script>
  function FetchPost() {
    let selectedBlog = document.getElementById("blog_id").value;
    $.post({
      url: "/blogs/fetch_post",
      contentType: "application/json;charset=UTF-8",
      data: JSON.stringify(selectedBlog),
      success: function (result) {
        console.log(result);
      },
    });
  }
</script>
{%endblock%}

flask_app/templates/existing.html
{% extends "user_default.html" %} {% block title %}Existing Blog{%endblock%}
{%block header%}
<style></style>

{%endblock%} {%block content%}

<div class="container my-5">
  <div class="container" style="width: 70%">
    <form
      class="row g-3 border border-warning py-2"
      action="{{url_for('blogs.existing')}}"
      method="POST"
    >
      <div class="col-12">
        <h3 class="text-light bg-warning text-center p-2">Create a Post</h3>
      </div>
      <div class="col-12">
        <label for="Blog Name" class="form-label">Blog Name</label>

        <select
          class="form-select border border-warning"
          name="blog_id"
          id="blog_id"
          required
        >
          <option value="" hidden selected>Select a blog category</option>
          {%for blog in blogs %}
          <option value="{{blog.id}}">{{blog.blog_name}}</option>
          {%endfor%}
        </select>
      </div>

      <div class="col-12">
        <label for="post_title" class="form-label">Post Title</label>
        <input
          type="text"
          class="form-control border border-warning"
          id="post_title"
          name="post_title"
          required
        />
      </div>

      <div class="col-12">
        <label for="post_description" class="form-label"
          >Post Description</label
        >
        <textarea
          class="form-control border border-warning"
          style="height: 250px !important"
          id="post_description"
          name="post_description"
          width="100%"
          required
        ></textarea>
      </div>

      <div class="col-12 d-flex justify-content-center">
        <button
          type="submit"
          class="btn btn-success"
          name="action"
          value="create_post"
        >
          Create Post
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "user_default.html" %} {% block title %}Dashboard{%endblock%} {%block
header%}
<style>
  .card:hover {
    opacity: 0.5;
  }
  a {
    text-decoration: none;
  }
</style>

{%endblock%} {%block content%}

<div class="container">
  <div class="row">
    <div class="col-6">
      <a href="/blogs/add">
        <div class="card m-5" style="width: 550px">
          <i
            class="fa fa-plus bg-warning text-center text-light"
            style="font-size: 150px"
            aria-hidden="true"
          ></i>
          <div class="card-body text-warning bg-light">
            <h4 class="card-title text-center">ADD BLOG</h4>
          </div>
        </div>
      </a>
    </div>
    <div class="col-6">
      <a href="/blogs/edit">
        <div class="card m-5" style="width: 430px">
          <i
            class="fa fa-refresh bg-light text-center text-warning"
            style="font-size: 150px"
            aria-hidden="true"
          ></i>
          <div class="card-body text-light bg-warning">
            <h4 class="card-title text-center">MODIFY BLOG</h4>
          </div>
        </div>
      </a>
    </div>


  </div>
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "user_default.html" %} {% block title %}Login{%endblock%} {%block
header%}
<style></style>

{%endblock%} {%block content%}

<div class="container my-5">
  <div class="container" style="width: 70%">
    <form
      class="row g-3 border border-warning py-2"
      action="{{url_for('login.index')}}"
      method="POST"
    >
      <div class="col-12">
        <h3 class="text-light bg-warning text-center p-2">Login</h3>
      </div>

      <div class="col-12">
        <label for="email_address" class="form-label">Email</label>
        <input
          type="email"
          class="form-control border border-warning"
          id="email_address"
          name="email_address"
          required
        />
      </div>

      <div class="col-12">
        <label for="password" class="form-label">Password</label>
        <input
          type="password"
          class="form-control border border-warning"
          id="password"
          name="password"
          required
        />
      </div>

      <div class="col-12 d-flex justify-content-center">
        <button
          type="submit"
          class="btn btn-success"
          name="action"
          value="login"
        >
          Login
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

flask_app/templates/show.html
{% extends "user_default.html" %} {% block title
%}{{blog.blog_name}}{%endblock%} {%block header%}
<style>
  .box_background {
    text-decoration: none;
    background-color: black !important;
  }
  .box:hover {
    opacity: 0.7;
  }
</style>
{%endblock%} {%block content%}

<div class="container">
  <h3 class="mt-5 bg-warning text-center text-light py-3">
    {{blog.blog_name}}
  </h3>
  {%for post in posts%}
  <div class="box row my-2">
    <div class="col-12">
      <div class="card text-center">
        <div class="card-body p-0">
          <h5 class="card-title">{{post.post_title}}</h5>
          <p class="card-text">{{post.post_description}}</p>
          <a
            href="/show/{{blog.blog_path}}/{{post.post_link}}"
            class="btn btn-primary"
            >Read more</a
          >
        </div>
      </div>
    </div>
  </div>
  {%endfor%}
</div>

{% endblock %}

flask_app/templates/show_post.html
{% extends "user_default.html" %} {% block title
%}{{blog.blog_name}}{%endblock%} {%block header%}
<style>
  .box_background {
    text-decoration: none;
    background-color: black !important;
  }
  .box:hover {
    opacity: 0.7;
  }
</style>
{%endblock%} {%block content%}

<div class="container">
  <h3 class="mt-5 bg-warning text-center text-light py-3">
    {{blog.blog_name}}
  </h3>

  <div class="box row my-2">
    <div class="col-12">
      <div class="card ps-2 pt-2">
        <div class="card-body p-0">
          <h5 class="card-title">{{posts.post_title}}</h5>
          <p class="card-text">{{posts.post_description}}</p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}